services:
  web-example:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn -k gevent --workers 4 --bind 0.0.0.0:5000 app:app
    volumes:
      - .:/app:ro
      - ./data:/app/data
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./static:/www/static:ro
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-example
    restart: always
