version: "3.5"

services:
  web-example:
    build:
      context: .
    # … остальные поля (ports, depends_on) оставьте без изменений …

    volumes:
      # ➊ исходный код монтируем «только‑чтение» (как было)
      - ./:/app:ro

      # ➋ новая папка для данных SQLite (read‑write)
      - ./data:/data            # ← папка data создастся рядом с compose‑файлом


    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./static:/www/static:ro
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf


