name: E2E нічні тести

on:
  schedule:
    - cron: "0 */2 * * *"   # кожні 2 години
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🐳 docker‑compose up
        run: docker compose up -d
      - uses: microsoft/playwright-github-action@v1
        with: { args: install --with-deps }
      - run: |
          npm ci
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
