name: Юніт‑тести та типи

on:
  push:
    paths: ["**/*.py", "tests/**"]
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        pyver: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: 🧪 pytest (py${{ matrix.pyver }} | ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "${{ matrix.pyver }}" }
      - run: |
          python -m pip install -r requirements.txt -r requirements-dev.txt
          pytest -q --cov=app || pytest -q   # якщо покриття не потрібно на Win
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-${{ matrix.pyver }}-${{ matrix.os }}
          path: .coverage*

  typing:
    runs-on: ubuntu-latest
    name: 🔤 mypy (Linux)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          pip install -r requirements-dev.txt -r requirements.txt
          mypy --ignore-missing-imports .
